version: '3.8'

services:
  backend:
    build: ./api
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - shared-data:/data
    networks:
      - app-network
    depends_on:
      kafka:
        condition: service_healthy
    
  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - REACT_APP_BASE_URL=127.0.0.1:8000
    ports:
      - "3000:3000"
    volumes:
      - shared-data:/data
    networks:
      - app-network
    depends_on:
      - backend

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: chat-app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./conf/db/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - shared-data:/var/lib/postgresql/data
    networks:
      - app-network
      
  kafka-consumer:
    container_name: kafka-consumer
    build: ./kafka_consumer
    volumes:
      - shared-data:/data
    networks:
      - app-network
    depends_on:
      kafka:
        condition: service_healthy
  
  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_HEAP_OPTS=-Xmx512M -Xms512M
    networks:
      - app-network
    healthcheck:
      test: kafka-topics.sh --bootstrap-server kafka:9092 --topic hc --create --if-not-exists && kafka-topics.sh --bootstrap-server kafka:9092 --topic hc --describe
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      - zookeeper

  kafka-ui:
    container_name: kafka-ui
    image: 'provectuslabs/kafka-ui:latest'
    ports:
      - '8080:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    networks:
      - app-network

  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  shared-data:
